### ISSUE TITLE
Wrong cropping on 3x image

### ISSUE THREAD

**Issue by brotkrueml** [b13/picture#1]
I am using the following snippet in my Fluid template:

`<i:image image="{myImage}" width="720c" height="405c" alt=""/>`

The original image has a dimension of 2638 x 1960 px.

A have the following TypoScript configuration:

`
plugin.tx_picture {
  useRetina = 1
  retina {
    2 = 2x
    3 = 3x
  }
}
`

So, the view helpers renders 1x, 2x and 3x:

`<img alt="" src="/files/_/c/7/csm_623745_78347e7582.png" width="720" height="405" class="" loading="lazy" srcset="/files/_/c/7/csm_623745_78347e7582.png, /files/_/c/7/csm_623745_e00ad6418a.png 2x, /files/_/c/7/csm_623745_12388fa823.png 3x">`

When I now check the sizes of the three scaled images, the dimension of the 3x image is not correct:

1x - 720 x 405
2x - 1440 x 810
3x - 2638 x 1960 - correct would be 2160 x 1215

**Comment by davidsteeb** [comment]
Hi Chris, 

thanks for noticing, I added a fix. Let me know in case this is not resolved.

**Comment by brotkrueml** [comment]
Hi David,
thanks for the quick fix. It works :-)
