### ISSUE TITLE
additionalAttributes not correctly assigned

### ISSUE THREAD

**Issue by brotkrueml** [b13/picture#3]
When using additionalAttributes on the image view helper, like:

    <i:image image="{image}" additionalAttributes="{decoding: 'async'}"/>

The decoding attribute is assigned to the source tag instead to the img tag, what is obviously wrong.

I digged into the code: As the source tag is rendered first the additional attributes are assigned first to the source tag and seem to be gone for the img tag. Sadly, the additional attributes are already merged to the attributes property of the view helper. I think, one approach to solve this could be to separate the additional attributes again from the default attributes and assign them always to the img tag.

What do you think?

**Comment by zebastiane** [comment]
Hi,
I have a similar problem but with the `style` attribute only rendered on the `source` tag.

**Comment by davidsteeb** [comment]
OK, finally had some time to test this. 
It seems this only happens when using an image-Tag without adding additional sources (for breakpoints).

This does not works:

```
<i:image src="{images.0.uid}" treatIdAsReference="1" maxWidth="300" additionalAttributes="{decoding: 'async'}" />
```

This does work:

```
<i:image src="{images.0.uid}" treatIdAsReference="1" maxWidth="300" additionalAttributes="{decoding: 'async'}" sources="{xl: '{maxWiddth: 403}'}" />
```

**Comment by davidsteeb** [comment]
I added a fix that resolves the issue for me. Could you guys check if there is some combination you're working with that is still a problem? Thank you!

**Comment by brotkrueml** [comment]
@davidsteeb Yep, looks good and works now correctly :-)

**Comment by davidsteeb** [comment]
Thank you!
