### ISSUE TITLE
Fallback src attribute for srcset is missing (IE11 Support)

### ISSUE THREAD

**Issue by Patta** [b13/picture#5]
If the `variants` attribute is set to render the `srcset` attribute, there is no fallback `src` attribute for the img tag.
Regardless whether the options `addWebp` or `useRetina` are enabled.

Without the `src` attribute, the image in never loaded in IE11. Which unfortunately is still a pre-installed web browser on windows and is actually still used.

Current srcset rendering:
```
<img 
width="400" height="200" 
title="" alt="" draggable="false"
srcset="https://mysite.site/small.jpg 320w, https://mysite.site/medium.jpg 640w, https://mysite.site/large.jpg 1024w" 
loading="lazy">
```

Recommended srcset rendering:
```
<img 
width="400" height="200" 
title="" alt="" draggable="false"
src="https://mysite.site/image.jpg" 
srcset="https://mysite.site/small.jpg 320w, https://mysite.site/medium.jpg 640w, https://mysite.site/large.jpg 1024w" 
loading="lazy">
```

It would be great if the src attribute could be integrated. 

By the way, this extension is very helpful and should be implemented in the core ;)

**Comment by davidsteeb** [comment]
Thank you!
